const TOPIC_LIST = {
  'basic-principles': [
    'Introduction to Ayurvedic Philosophy',
    'Tridosha Theory: Vata, Pitta, Kapha',
    'Concept of Sapta Dhatu (Seven Tissues)',
    'Trayodasha Agni (Thirteen Types of Fire)',
    'Ama (Metabolic Toxins) and its Management',
    'Prakriti: Determining Body Constitution',
    'Dinacharya: The Daily Regimen for Health',
    'Ritucharya: Seasonal Regimen and Transitions',
    'Introduction to Srotas (Channels of Circulation)',
    'Ojas: The Essence of Vitality and Immunity',
    'Trividha Upasthambha: Diet, Sleep, and Celibacy',
    'Manas: The Ayurvedic Concept of Mind',
    'Shad-padartha: The Six Categories of Existence',
    'Nidan Panchaka: The Five Tools of Diagnosis',
    'Shat-kriya-kala: The Six Stages of Disease Cycle',
    'Janapadodhwansa: Ayurvedic View on Epidemics',
    'Langhana and Brimhana: Depletion and Nourishment',
    'Deepana and Pachana: Enhancing Digestion',
    'Sneha and Sweda: Foundational Preparatory Therapies',
    'Koshta and Agni Analysis for Treatment',
    'Shodhana vs Shamana: Purification vs Palliation',
    'Vyadhikshamatva: Concept of Resilience',
    'Ahara Vidhi: Ayurvedic Rules of Eating',
    'Vihara: Guidelines for Healthy Living',
    'Historical Evolution of Ayurvedic Samhitas'
  ],
  'kriya-sharir': [
    'Functional Classification of Doshas',
    'Vata Dosha Subtypes and Their Functions',
    'Pitta Dosha Subtypes and Their Functions',
    'Kapha Dosha Subtypes and Their Functions',
    'Dhatu Poshana Nyaya: Laws of Tissue Nutrition',
    'Rasa Dhatu: Formation and Physiological Role',
    'Rakta Dhatu: Oxygenation and Life Sustenance',
    'Mamsa Dhatu: Structure and Physical Integrity',
    'Meda Dhatu: Metabolism and Lubrication',
    'Asthi Dhatu: Support and Skeleton Stability',
    'Majja Dhatu: Marrow and Nervous Coordination',
    'Shukra Dhatu: Reproduction and Creative Energy',
    'Mala Kriya: Processes of Waste Elimination',
    'Purisha and Mutra: Formation and Abnormalities',
    'Sveda: Regulating Temperature and Skin Health',
    'Atma and Indriya: Union of Soul and Senses',
    'Nidra: The Physiology of Rest and Sleep',
    'Artava and Stanya: Female Specific Physiology',
    'Garbha Sambhava: Factors for Healthy Conception',
    'Prakriti Nirmana: The Moment of Constitution',
    'Deha Bala: Physical and Biological Strength',
    'Kriya-Kala: Physiological Stages of Digestion',
    'Upadhatu: Secondary Tissues and Their Roles'
  ],
  'rachana-sharir': [
    'Sharir Paribhasha: Anatomical Terminology',
    'Garbha Sharir: Embryonic Development',
    'Asthi Sharir: Classification of the Skeleton',
    'Sandhi Sharir: Joint Structure and Function',
    'Snayu and Kandra: Tendons and Ligaments',
    'Vascular Rachana: Sira, Dhamani, and Srotas',
    'Marma Sharir: 107 Vital Clinical Points',
    'Indriya Sharir: Anatomy of Sense Organs',
    'Koshtha and Ashaya: Visceral Organs Structure',
    'Kala Sharir: Seven Essential Membranes',
    'Twak Sharir: Layers of Skin in Ayurveda',
    'Peshi Sharir: Detailed Study of Muscles',
    'Srotas Rachana: Specialized Systems Structure',
    'Nervous System: Vata Vaha Sansthan Anatomy',
    'Lymphatic System in Ayurvedic Anatomy',
    'Surface and Regional Anatomy Concepts',
    'Anguli Pramana: Anthropometric Measurements',
    'Historical Review of Cadaveric Dissection',
    'Clinical Anatomy of Vital Organs',
    'Structural Evolution of Human Body'
  ],
  'dravyaguna-vigyan': [
    'Introduction to Ayurvedic Pharmacology',
    'Rasa: The Six Tastes and Their Effects',
    'Guna: The 20 Attributes of Substances',
    'Virya: Concepts of Thermal Potency',
    'Vipaka: Post-Digestive Transformation',
    'Prabhava: Specific Pharmaceutical Action',
    'Bheshaja Pariksha: Drug Identification',
    'Classification of Medicinal Plants',
    'Ashwagandha: The King of Adaptogens',
    'Tulsi: The Holy Basil and Immunity',
    'Guduchi: Rejuvenative and Anti-pyretic',
    'Amalaki: The Best Source of Rasa',
    'Triphala: The Universal Digestive Tonic',
    'Shatavari: The Ayurvedic Female Tonic',
    'Brahmi: Cognitive and Mental Health',
    'Haridra: Curcumin and its Clinical Uses',
    'Guggulu: Management of Vata and Meda',
    'Arjuna: Ayurvedic Cardiac Care',
    'Neem: Anti-microbial and Purification',
    'Vacha: Speech and Neurological Support',
    'Shunthi: The Universal Medicine',
    'Pippali: Respiratory and Bioavailability',
    'Maricha: The Pungent Stimulant',
    'Dravyaguna Research Methedologies',
    'Nighantu: Historical Lexicons of Herbs'
  ],
  'rog-nidan': [
    'Nidan Panchaka: The Diagnostic Suite',
    'Shat-Kriya-Kala: Pathological Progression',
    'Samanya Samprapti: General Pathogenesis',
    'Ashtavidha Pariksha: Eight-fold Examination',
    'Dashavidha Pariksha: Ten-fold Patient Study',
    'Nadi Pariksha: Pulse Diagnosis Mastery',
    'Mutra and Jihva Pariksha: Urine and Tongue',
    'Introduction to Srotodusthi Abnormalities',
    'Vikriti Vigyan: Pathology of Tridoshas',
    'Diagnosis of Jwara (Fevers)',
    'Diagnosis of Prameha (Metabolic Disorders)',
    'Diagnosis of Raktapitta (Bleeding Disorders)',
    'Diagnosis of Kushtha (Skin Pathologies)',
    'Ama Nidan: Detecting Metabolic Toxins',
    'Modern Lab Correlations in Nidan',
    'Arishta Lakshana: Prognostic Indicators',
    'Differential Diagnosis in Ayurveda',
    'Imaging and Scanning in Rog Nidan',
    'Psychological Assessment (Manas Pariksha)',
    'Standardization of Diagnostic Protocols'
  ],
  'kayachikitsa': [
    'Introduction to Systemic Medicine',
    'Management of Jwara (All Types of Fever)',
    'Raktapitta: Management of Hemorrhages',
    'Prameha and Madhumeha (Diabetes Care)',
    'Kushtha: Treatment of Skin Diseases',
    'Shwasa and Kasa: Respiratory Management',
    'Pandu and Kamala: Liver and Blood Care',
    'Grahani and Atisara: Digestive Disorders',
    'Arsha: Management of Hemorrhoids',
    'Amavata: Rheumatoid Arthritis Protocol',
    'Sandhigatavata: Osteoarthritis Management',
    'Kayachikitsa in Neurological Disorders',
    'Endocrine Disorders in Ayurveda',
    'Rasayana: Rejuvenation Therapy',
    'Vajikarana: Aphrodisiac and Virility',
    'Management of Chronic Kidney Diseases',
    'Ayurvedic Oncology: Arbuda Chikitsa',
    'Cardiac Care in Kayachikitsa',
    'Psychiatric Disorders (Unmada & Apasmara)',
    'Geriatric Care in Ayurveda',
    'Principles of Aushadha Matra (Dosage)',
    'Anupana: The Importance of Vehicles',
    'Samsarjana Krama: Post-therapy Diet',
    'Pathya-Apathya in Clinical Practice',
    'Emergency Management in Kayachikitsa'
  ],
  'panchakarma': [
    'Fundamentals of Shodhana (Purification)',
    'Poorva Karma: Prep via Snehana (Oleation)',
    'Poorva Karma: Prep via Swedana (Sudation)',
    'Vamana: Therapeutic Emesis Procedure',
    'Virechana: Therapeutic Purgation',
    'Basti: The Half of All Treatments',
    'Anuvasana and Niruha Basti Types',
    'Nasya: Treatment for Supra-clavicular Organs',
    'Raktamokshana: Bloodletting Techniques',
    'Jalaukavacharana: Leech Therapy',
    'Sirodhara: The Science of Bliss',
    'Kati, Janu, and Griva Basti (External)',
    'Pinda Sweda: Bolus Massage Techniques',
    'Udvartana: Herbal Powder Massage',
    'Panchakarma in Pediatric Practice',
    'Panchakarma for Post-partum Care',
    'Paschat Karma: Post-procedural Care',
    'Complications and Management (Vyapat)',
    'Equipment and Infrastructure for PK',
    'Standard Operating Procedures for PK',
    'Physiotherapy and Panchakarma',
    'Keraliya Panchakarma Specialities',
    'Panchakarma in Lifestyle Disorders',
    'Detoxification and Life Extension',
    'Practical Demonstration of Vamana'
  ],
  'rasashastra': [
    'Paribhasha: Rasashastra Terminology',
    'Yantra and Musha: Lab Equipment',
    'Puta and Agni: Heating Devices',
    'Parada: Mercury Purification (Shodhana)',
    'Ashta-Samskara: Eight Stages of Mercury',
    'Maharasa and Uparasa Groups',
    'Sadharana Rasa and Ratna Vijnana',
    'Shodhana and Marana Processes',
    'Bhasma: Nanomedicine of Ayurveda',
    'Satwa Patana: Metal Extraction',
    'Kupipakwa Kalpana: Sublimation products',
    'Parpati Kalpana: Thin Sheet Preparations',
    'Pottali Kalpana: Bolus Medicines',
    'Khalviya Rasayana: Triturated products',
    'Bhaishajya Kalpana: Pharmacy Principles',
    'Swarasa, Kalka, and Kwatha Basics',
    'Sneha Kalpana: Medicated Oils and Ghee',
    'Asava and Arishta: Fermentation Science',
    'Lehya and Guggat-Kalpana',
    'Standardization of Rasaushadhi',
    'Safety and Toxicity of Heavy Metals',
    'Drug Regulatory Acts in Ayurveda',
    'Modern QC for Ayurvedic Drugs'
  ],
  'agadtantra': [
    'Introduction to Ayurvedic Toxicology',
    'Sthavara Visha: Plant and Mineral Poisons',
    'Jangama Visha: Animal Venoms (Snakes, etc.)',
    'Visha Vega: Stages of Poisoning',
    'Management of Snake Bites (Sarpavisha)',
    'Management of Insect Bites',
    'Garavisha and Dushi Visha (Latent toxins)',
    'Drug and Alcohol Addictions in Ayurveda',
    'Environmental Toxicology (Dushi Desha)',
    'Forensic Medicine: Vyavahara Ayurveda',
    'Legal Aspects of Medical Practice',
    'Asphyxia and Death Investigation',
    'Identification Paradigms in Forensics',
    'Emergency Antidotes in Agadtantra',
    'Occupational Hazards and Ayurveda'
  ],
  'shalya-tantra': [
    'Sushruta: The Father of Surgery',
    'Yantra and Shastra: Surgical Instruments',
    'Trividha Karma: Pre, Intra, and Post-op',
    'Ashtavidha Shastra Karma (8 Procedures)',
    'Vrana: Management of Wounds',
    'Bandhana: Ayurvedic Bandaging Techniques',
    'Kshara Sutra: Management of Fistula',
    'Agni Karma: Thermal Cautery',
    'Raktamokshana in Shalya Surgery',
    'Fractures and Dislocations (Bhagna)',
    'Management of Head Injuries',
    'Abdominal Surgery in Classics',
    'Urinary Calculi (Ashmari) Management',
    'Anorectal Disorders Treatment',
    'Blood Transfusion and Fluid Balance',
    'Pain Management and Anesthesia',
    'Ophthalmic Surgery (Shalakya Intro)',
    'Plastic Surgery and Reconstruction',
    'Modern Surgical Correlations',
    'Emergency Trauma Care in Shalya'
  ],
  'shalakya-tantra': [
    'Introduction to Shalakya Tantra',
    'Eye Anatomy (Netra Rachana)',
    'Eye Physiology (Netra Kriya)',
    'Classification of Eye Diseases (Netra Roga)',
    'Management of Conjunctivitis (Abhishyanda)',
    'Management of Cataract (Linga-nasha)',
    'Glaucoma (Adhimantha) in Ayurveda',
    'Anatomy and Diseases of the Ear (Karna Roga)',
    'Nasal Disorders (Nasa Roga)',
    'Oral Cavity Diseases (Mukha Roga)',
    'Throat Disorders (Kantha Roga)',
    'Headaches (Shiroroga) in Shalakya',
    'Kriyakalpa: Specialized Ocular Therapies',
    'Netra Tarpana and Putapaka',
    'Shiro-basti and Nasya in Shalakya'
  ],
  'prasuti-tantra': [
    'Anatomy of Female Reproductive System (Stri-Shartira)',
    'Menstrual Cycle (Artava Chakra)',
    'Concept of Yoni-vyapad (Gynaecological Disorders)',
    'Management of Pradara (Leucorrhoea/Menorrhagia)',
    'Infertility (Vandhyatva) in Ayurveda',
    'Antenatal Care (Garbhini Paricharya)',
    'Development of Foetus (Garbha Vriddhi)',
    'Complications of Pregnancy (Garbha Vyapad)',
    'Normal Labour (Prasava) in Ayurveda',
    'Postnatal Care (Sutika Paricharya)',
    'Breast Milk and Lactation (Stanya)',
    'Menopause (Rajonivritti) Management',
    'Ayurvedic Contraception',
    'Gynaecological Procedures (Yoni Prakshalana, etc.)',
    'Surgical Interventions in Prasuti'
  ],
  'kaumarbhritya': [
    'Introduction to Ayurvedic Pediatrics',
    'Care of the Newborn (Navajata Shishu)',
    'Breastfeeding and Wet-nursing (Dhatri)',
    'Growth and Development (Vardhamana)',
    'Dentition (Dantotpatti) in Children',
    'Pediatric Nutrition (Ahara)',
    'Common Pediatric Ailments (Balagraha, etc.)',
    'Management of Diarrhoea and Fever in Children',
    'Respiratory Disorders in Pediatrics',
    'Skin Diseases in Children',
    'Developmental Delays and Disabilities',
    'Panchakarma for Children',
    'Samskaras: Rites of Passage for Health',
    'Ayurvedic Vaccination (Lehana Karma)',
    'Emergency Pediatric Care'
  ],
  'swasthavritta': [
    'Definition of Health (Swastha)',
    'Dinacharya: Daily Regimen for Health',
    'Ritucharya: Seasonal Regimen',
    'Dietetics (Ahara-vidhi) in Swasthavritta',
    'Importance of Sleep and Celibacy',
    'Concept of Vegaroha (Urges)',
    'Social Health (Janapadodhvansa)',
    'Occupational Health in Ayurveda',
    'Principles of Yoga and Pranayama',
    'Shat-karma: Yogic Cleansing',
    'Asanas for Holistic Health',
    'Meditation (Dhyana) and Mental Health',
    'Naturopathy and Ayurveda',
    'Global Health and Ayurveda',
    'Geriatric Preventive Care'
  ]
};

const TOPIC_LIST_MR = {
  'basic-principles': [
    'आयुर्वेदिक तत्त्वज्ञानाचा परिचय',
    'त्रिदोष सिद्धांत: वात, पित्त, कफ',
    'सप्त धातूंची संकल्पना',
    'त्रयोदश अग्नी (१३ प्रकारचे अग्नी)',
    'आम (चयापचय विष) आणि त्याचे व्यवस्थापन',
    'प्रकृती: शरीर प्रकृती निश्चित करणे',
    'दिनचर्या: आरोग्यासाठी दैनिक नियम',
    'ऋतूचर्या: ऋतूमान पद्धती आणि संक्रमण',
    'स्त्रोतसांचा परिचय (अभिसरण वाहिन्या)',
    'ओज: चैतन्य आणि रोगप्रतिकारशक्तीचे सार',
    'त्रिविध उपस्तंभ: आहार, निद्रा आणि ब्रह्मचर्य',
    'मानस: आयुर्वेदातील मनाची संकल्पना',
    'षड्-पदार्थ: अस्तित्वाच्या सहा श्रेणी',
    'निदान पंचक: निदानाची पाच साधने',
    'षट्-क्रिया-काल: रोगाच्या चक्राचे सहा टप्पे',
    'जनपदोद्ध्वंस: साथीच्या रोगांवर आयुर्वेदिक दृष्टिकोन',
    'लंघन आणि बृंहण: घट आणि पोषण',
    'दीपन आणि पाचन: पचनशक्ती वाढवणे',
    'स्नेह आणि स्वेद: मूलभूत पूर्वतयारी उपचार',
    'उपचारासाठी कोष्ठ आणि अग्नी विश्लेषण',
    'शोधन विरुद्ध शमन: शुद्धीकरण विरुद्ध उपशमन',
    'व्याधिक्षमत्व: लवचिकतेची संकल्पना',
    'आहार विधी: जेवण्याचे आयुर्वेदिक नियम',
    'विहार: निरोगी जीवनासाठी मार्गदर्शक तत्त्वे',
    'आयुर्वेदिक संहितेची ऐतिहासिक उत्क्रांती'
  ],
  'kriya-sharir': [
    'दोषांचे कार्यात्मक वर्गीकरण',
    'वात दोषाचे उपप्रकार आणि त्यांची कार्ये',
    'पित्त दोषाचे उपप्रकार आणि त्यांची कार्ये',
    'कफ दोषाचे उपप्रकार आणि त्यांची कार्ये',
    'धातू पोषण न्याय: ऊती पोषणाचे नियम',
    'रस धातू: निर्मिती आणि शारीरिक भूमिका',
    'रक्त धातू: प्राणवायू आणि जीवन निर्वाह',
    'मांस धातू: रचना आणि शारीरिक अखंडता',
    'मेद धातू: चयापचय आणि वंगण',
    'अस्थी धातू: आधार आणि सांगाड्याची स्थिरता',
    'मज्जा धातू: मज्जा आणि मज्जासंस्थेचा समन्वय',
    'शुक्र धातू: पुनरुत्पादन आणि सर्जनशील ऊर्जा',
    'मल क्रिया: कचरा निर्मूलनाची प्रक्रिया',
    'पुरीष आणि मूत्र: निर्मिती आणि विकृती',
    'स्वेद: तापमान नियंत्रण आणि त्वचेचे आरोग्य',
    'आत्मा आणि इंद्रिय: आत्मा आणि संवेदनांचे मिलन',
    'निद्रा: विश्रांती आणि झोपेचे शरीरविज्ञान',
    'आर्तव आणि स्तन्य: स्त्रियांचे विशिष्ट शरीरविज्ञान',
    'गर्भ संभव: निरोगी गर्भधारणेसाठी घटक',
    'प्रकृती निर्माण: प्रकृतीचा क्षण',
    'देह बल: शारीरिक आणि जैविक शक्ती',
    'क्रिया-काल: पचनाचे शरीरवैज्ञानिक टप्पे',
    'उपधातू: दुय्यम ऊती आणि त्यांच्या भूमिका'
  ],
  'rachana-sharir': [
    'शरीर परिभाषा: शरीरशास्त्रीय शब्दावली',
    'गर्भ शरीर: भ्रूण विकास',
    'अस्थी शरीर: सांगाड्याचे वर्गीकरण',
    'संधी शरीर: सांध्यांची रचना आणि कार्य',
    'स्नायू आणि कंडरा: स्नायू आणि अस्थिबंध',
    'रक्तवाहिन्यांची रचना: सिरा, धमनी आणि स्त्रोतस',
    'मर्म शरीर: १०७ महत्त्वाचे क्लिनिकल मुद्दे',
    'इंद्रिय शरीर: ज्ञानेंद्रियांची रचना',
    'कोष्ठ आणि आशय: अंतर्गत अवयवांची रचना',
    'कला शरीर: सात महत्त्वाचे पडदे',
    'त्वचा शरीर: आयुर्वेदातील त्वचेचे स्तर',
    'पेशी शरीर: स्नायूंचा तपशीलवार अभ्यास',
    'स्त्रोतस रचना: विशेष संस्थांची रचना',
    'मज्जासंस्था: वात वह संस्था शरीरशास्त्र',
    'आयुर्वेदिक शरीरशास्त्रातील लिम्फॅटिक सिस्टम',
    'पृष्ठभाग आणि प्रादेशिक शरीरशास्त्र संकल्पना',
    'अंगुली प्रमाण: मानववंशशास्त्रीय मोजमाप',
    'शवविच्छेदनाचा ऐतिहासिक आढावा',
    'महत्त्वाच्या अवयवांचे क्लिनिकल शरीरशास्त्र',
    'मानवी शरीराची संरचनात्मक उत्क्रांती'
  ],
  'dravyaguna-vigyan': [
    'आयुर्वेदिक औषधशास्त्राचा परिचय',
    'रस: सहा चवी आणि त्यांचे परिणाम',
    'गुण: पदार्थांचे २० गुणधर्म',
    'वीर्य: उष्ण आणि शीत वीर्य संकल्पना',
    'विपाक: पचनानंतरचे रूपांतर',
    'प्रभाव: विशिष्ट औषधी क्रिया',
    'भेषज परीक्षा: औषध ओळख',
    'औषधी वनस्पतींचे वर्गीकरण',
    'अश्वगंधा: औषधी वनस्पतींचा राजा',
    'तुळस: पवित्र तुळस आणि रोगप्रतिकारशक्ती',
    'गुुडुची/गुळवेल: पुनरुज्जीवन आणि ज्वरशामक',
    'आमलाकी/आवळा: रसाचा उत्तम स्रोत',
    'त्रिफळा: सार्वत्रिक पाचक टॉनिक',
    'शतावरी: आयुर्वेदिक स्त्रियांचे टॉनिक',
    'ब्राह्मी: संज्ञानात्मक आणि मानसिक आरोग्य',
    'हरिद्रा/हळद: कुरकुमीन आणि त्याचे क्लिनिकल उपयोग',
    'गुग्गुळ: वात आणि मेद व्यवस्थापन',
    'अर्जुन: आयुर्वेदिक हृदय निगा',
    'कडुनिंब: प्रतिजैविक आणि शुद्धीकरण',
    'वचा: वाणी आणि न्यूरोलॉजिकल समर्थन',
    'सुंठ: सार्वत्रिक औषध',
    'पिंपळी: श्वसन आणि जैवउपलब्धता',
    'मरीच: तिखट उत्तेजक',
    'द्रव्यगुण संशोधन पद्धती',
    'निघंटू: औषधी वनस्पतींचे ऐतिहासिक शब्दकोश'
  ],
  'rog-nidan': [
    'निदान पंचक: निदानाची पाच साधने',
    'षट्-क्रिया-काल: रोगाची प्रगती',
    'सामान्य संप्राप्ती: सामान्य रोगनिर्मिती',
    'अष्टविध परीक्षा: आठ प्रकारची तपासणी',
    'दशविध परीक्षा: दहा प्रकारचे रुग्ण अध्ययन',
    'नाडी परीक्षा: नाडी निदानात प्रभुत्व',
    'मूत्र आणि जिव्हा परीक्षा: मूत्र आणि जीभ',
    'स्त्रोतदुष्टी विकृतींचा परिचय',
    'विकृती विज्ञान: त्रिदोषांचे रोगशास्त्र',
    'ज्वर (ताप) चे निदान',
    'प्रमेह (मधुमेह) चे निदान',
    'रक्तपित्त (रक्तस्त्राव विकार) चे निदान',
    'कुष्ठ (त्वचा रोग) चे निदान',
    'आम निदान: चयापचय विष शोधणे',
    'निदानातील आधुनिक प्रयोगशाळा सहसंबंध',
    'अरिष्ट लक्षण: भविष्यातील सूचक चिन्हे',
    'आयुर्वेदातील विभेदक निदान',
    'रोग निदानातील इमेजिंग आणि स्कॅनिंग',
    'मानसिक मूल्यांकन (मानस परीक्षा)',
    'निदान प्रोटोकॉलचे मानकीकरण'
  ],
  'kayachikitsa': [
    'सिस्टेमिक मेडिसिनचा परिचय',
    'ज्वर व्यवस्थापन (तापाचे सर्व प्रकार)',
    'रक्तपित्त: रक्तस्त्राव व्यवस्थापन',
    'प्रमेह आणि मधुमेह निगा',
    'कुष्ठ: त्वचा रोगांचे उपचार',
    'श्वास आणि कास: श्वसन व्यवस्थापन',
    'पांडू आणि कामला: यकृत आणि रक्त निगा',
    'ग्रहणी आणि अतिसार: पचन विकार',
    'अर्श: मूळव्याध व्यवस्थापन',
    'आमवात: संधिवात प्रोटोकॉल',
    'संधीगतवात: ऑस्टियोआर्थरायटिस व्यवस्थापन',
    'न्यूरोलॉजिकल विकारांमध्ये कायचिकित्सा',
    'आयुर्वेदातील अंतःस्रावी विकार',
    'रसायन: कायाकल्प थेरपी',
    'वाजीकरण: कामोत्तेजक आणि पुरुषत्व',
    'जुनाट किडनी रोगांचे व्यवस्थापन',
    'आयुर्वेदिक ऑन्कोलॉजी: अर्बुद चिकित्सा',
    'कायचिकित्सामधील हृदय निगा',
    'मानसिक विकार (उन्माद आणि अपस्मार)',
    'आयुर्वेदातील वृद्ध निगा',
    'औषध मात्रा (डोस) ची तत्त्वे',
    'अनुपान: वाहनांचे महत्त्व',
    'संसर्जन क्रम: उपचारानंतरचा आहार',
    'क्लिनिकल प्रॅक्टिसमध्ये पथ्य-अपथ्य',
    'कायचिकित्सामधील आपत्कालीन व्यवस्थापन'
  ],
  'panchakarma': [
    'शोधन (शुद्धीकरण) ची मूलभूत तत्त्वे',
    'पूर्व कर्म: स्नेहन (तैल मर्दन)',
    'पूर्व कर्म: स्वेदन (वाफ)',
    'वमन: उपचारात्मक उलट्यांची प्रक्रिया',
    'विरेचना: उपचारात्मक रेचक',
    'बस्ती: अर्धी चिकित्सा',
    'अनुवासन आणि निरूह बस्ती प्रकार',
    'नस्य: शिरोभागातील अवयवांसाठी उपचार',
    'रक्तमोक्षण: रक्त काढण्याचे तंत्र',
    'जलौकावचरण: जळू थेरपी',
    'शिरोधारा: आनंदाचे विज्ञान',
    'कटी, जानू आणि ग्रीवा बस्ती (बाह्य)',
    'पिंड स्वेद: पोटली मालिश तंत्र',
    'उद्वर्तन: हर्बल पावडर मसाज',
    'बालरोग प्रॅक्टिसमध्ये पंचकर्म',
    'प्रसूतीनंतरच्या सुश्रूषेसाठी पंचकर्म',
    'पश्चात कर्म: प्रक्रियेनंतरची काळजी',
    'गुंतागुंत आणि व्यवस्थापन (व्यापत)',
    'पंचकर्मासाठी उपकरणे आणि पायाभूत सुविधा',
    'पंचकर्मासाठी मानक कार्यप्रणाली (SOP)',
    'फिजिओथेरपी आणि पंचकर्म',
    'केरलीय पंचकर्म वैशिष्ट्ये',
    'जीवनशैली विकारांमध्ये पंचकर्म',
    'डिटॉक्सिफिकेशन आणि आयुर्मान वाढवणे',
    'वमनचे व्यावहारिक प्रात्यक्षिक'
  ],
  'rasashastra': [
    'परिभाषा: रसशास्त्र शब्दावली',
    'यंत्र आणि मूषा: प्रयोगशाळा उपकरणे',
    'पुट आणि अग्नी: गरम करण्याची साधने',
    'पारद: पारा शुद्धीकरण (शोधन)',
    'अष्ट-संस्कार: पाऱ्याचे आठ टप्पे',
    'महारस आणि उपररस गट',
    'साधारण रस आणि रत्न विज्ञान',
    'शोधन आणि मारण प्रक्रिया',
    'भस्म: आयुर्वेदाचे नॅनोमेडिसिन',
    'सत्व पातन: धातू काढणे',
    'कुपीपक्व कल्पना: उदात्तीकरण उत्पादने',
    'पर्पटी कल्पना: पातळ पत्रा औषधे',
    'पोटली कल्पना: पोटली औषधे',
    'खल्वीय रसायन: खल केलेली उत्पादने',
    'भैषज्य कल्पना: फार्मसी तत्त्वे',
    'स्वरस, कल्क आणि क्वाथ मूलभूत गोष्टी',
    'स्नेह कल्पना: औषधी तेल आणि तूप',
    'आसव आणि अरिष्ट: किण्वन विज्ञान',
    'लेह आणि गुग्गुळ-कल्पना',
    'रसौषधींचे मानकीकरण',
    'जड धातूंची सुरक्षितता आणि विषारीपणा',
    'आयुर्वेदातील औषध नियामक कायदे',
    'आयुर्वेदिक औषधांसाठी आधुनिक QC'
  ],
  'agadtantra': [
    'आयुर्वेदिक विषशास्त्राचा परिचय',
    'स्थावर विष: वनस्पती आणि खनिज विष',
    'जंगम विष: प्राणी विष (साप इ.)',
    'विष वेग: विषबाधेचे टप्पे',
    'सर्पदंश व्यवस्थापन (सर्पविष)',
    'कीटक दंशाचे व्यवस्थापन',
    'गरविष आणि दूषी विष (सुप्त विष)',
    'आयुर्वेदातील अंमली पदार्थ आणि मद्यपान व्यसन',
    'पर्यावरण विषशास्त्र (दूषी देश)',
    'फॉरेन्सिक मेडिसिन: व्यवहार आयुर्वेद',
    'वैद्यकीय सरावचे कायदेशीर पैलू',
    'श्वास कोंडणे आणि मृत्यूची तपासणी',
    'फॉरेन्सिकमधील ओळख निकष',
    'अगदतंत्रातील आपत्कालीन उतारा',
    'व्यावसायिक धोके आणि आयुर्वेद'
  ],
  'shalya-tantra': [
    'सुश्रुत: शस्त्रक्रियेचे जनक',
    'यंत्र आणि शस्त्र: शस्त्रक्रिया साधने',
    'त्रिविध कर्म: शस्त्रक्रियापूर्वी, वेळी आणि नंतर',
    'अष्टविध शस्त्र कर्म (८ प्रक्रिया)',
    'व्रण: जखमांचे व्यवस्थापन',
    'बंधन: आयुर्वेदिक मलमपट्टी तंत्र',
    'क्षार सूत्र: भगंदर व्यवस्थापन',
    'अग्निकर्म: थर्मल कॉटरी',
    'शल्य शस्त्रक्रियेत रक्तमोक्षण',
    'अस्थिभंग आणि विस्थापन (भग्न)',
    'डोक्याच्या दुखापतींचे व्यवस्थापन',
    'क्लासिक्समध्ये पोटाची शस्त्रक्रिया',
    'मूत्रखडा (अश्मरी) व्यवस्थापन',
    'गुदद्वाराच्या विकारांवर उपचार',
    'रक्त संक्रमण आणि द्रव संतुलन',
    'वेदना व्यवस्थापन and भूल',
    'नेत्र शस्त्रक्रिया (शाालक्य परिचय)',
    'प्लास्टिक सर्जरी आणि पुनर्रचना',
    'आधुनिक सर्जिकल सहसंबंध',
    'शल्यमधील आपत्कालीन आघात निगा'
  ],
  'shalakya-tantra': [
    'शाालक्य तंत्राचा परिचय',
    'नेत्र रचना (डोळ्यांची रचना)',
    'नेत्र क्रिया (डोळ्यांचे कार्य)',
    'डोळ्यांच्या रोगांचे वर्गीकरण',
    'नेत्राभिष्यंद (Conjunctivitis) व्यवस्थापन',
    'लिंगनाश (Cataract) व्यवस्थापन',
    'आयुर्वेदातील अधिर्मंथ (Glaucoma)',
    'कर्ण रोग (कान) रचना आणि आजार',
    'नासा रोग (नाक विकार)',
    'मुख रोग (तोंडाचे आजार)',
    'कंठ रोग (घशाचे विकार)',
    'शाालक्य मध्ये शिरोरोग (डोकेदुखी)',
    'क्रियाकल्प: विशेष नेत्र चिकित्सा',
    'नेत्र तर्पण आणि पुटपाक',
    'शाालक्य मध्ये शिरो-बस्ती आणि नस्य'
  ],
  'prasuti-tantra': [
    'स्त्री प्रजनन संस्थेची रचना (स्त्री-शरीर)',
    'आर्तव चक्र (मासिक पाळी)',
    'योनी-व्यापद संकल्पना (स्त्रीरोग)',
    'प्रदर व्यवस्थापन (धुपणी/अतिस्त्राव)',
    'आयुर्वेदातील वंध्यत्व (Vandhyatva)',
    'गर्भिणी परिचर्या (प्रसूतीपूर्व निगा)',
    'गर्भाचा विकास (गर्भ वृद्धी)',
    'गर्भधारणेतील गुंतागुंत (गर्भ व्यापद)',
    'आयुर्वेदातील नैसर्गिक प्रसूती (Prasava)',
    'सुतिका परिचर्या (प्रसूतीनंतरची निगा)',
    'स्तन्य (आईचे दूध) आणि स्तनपान',
    'रजोनिवृत्ती (Menopause) व्यवस्थापन',
    'आयुर्वेदिक कुटुंब नियोजन',
    'स्त्रीरोगविषयक प्रक्रिया (योनी प्रक्षालन, इ.)',
    'प्रसूतीमधील शस्त्रक्रिया हस्तक्षेप'
  ],
  'kaumarbhritya': [
    'आयुर्वेदिक बालरोगाचा परिचय',
    'नवजात शिशूची निगा (Navajata Shishu)',
    'स्तनपान आणि धात्री',
    'वाढ आणि विकास (वर्धमान)',
    'मुलांमध्ये दंतोद्भव (दात येणे)',
    'बालरोग पोषण (आहार)',
    'सामान्य बालपण आजार (बालग्रह, इ.)',
    'मुलांमधील अतिसार आणि तापाचे व्यवस्थापन',
    'बालरोगातील श्वसन विकार',
    'मुलांमधील त्वचा रोग',
    'विकासात्मक विलंब आणि अपंगत्व',
    'मुलांसाठी पंचकर्म',
    'संस्कार: आरोग्यासाठी संस्कार',
    'आयुर्वेदिक लसीकरण (लेहन कर्म)',
    'आपत्कालीन बालरोग निगा'
  ],
  'swasthavritta': [
    'आरोग्याची व्याख्या (स्वस्थ)',
    'दिनचर्या: आरोग्यासाठी दैनंदिन नियम',
    'ऋतूचर्या: ऋतूमान आहार-विहार',
    'स्वस्थवृत्तामधील आहारशास्त्र',
    'झोप आणि ब्रह्मचर्याचे महत्त्व',
    'वेगाच्या संकल्पना (अधम्य वेग)',
    'सामाजिक आरोग्य (जनपदोद्ध्वंस)',
    'आयुर्वेदातील व्यावसायिक आरोग्य',
    'योग आणि प्राणायाम तत्त्वे',
    'षट्-कर्म: यौगिक शुद्धीकरण',
    'समग्र आरोग्यासाठी आसने',
    'ध्यान आणि मानसिक आरोग्य',
    'निसर्गोपचार आणि आयुर्वेद',
    'जागतिक आरोग्य आणि आयुर्वेद',
    'वृद्धापकाळातील प्रतिबंधात्मक निगा'
  ]
};

module.exports = { TOPIC_LIST, TOPIC_LIST_MR };
